/*******************************************************************************
  * Copyright (c) 13.11.2016 Thomas Zierer.
  * All rights reserved. This program and the accompanying materials
  * are made available under the terms of the Eclipse Public License v1.0
  * which accompanies this distribution, and is available at
  * http://www.eclipse.org/legal/epl-v10.html
  *
  * Contributors:
  *    Thomas Zierer - initial API and implementation and/or initial documentation
  *******************************************************************************/
package de.tgmz.sonar.plugins.xinfo.color.cobol;

/**
 * COBOL keywords.
 */
public enum ReservedWords {
	//CHECKSTYLE DISABLE LineLength
	ACCEPT, ACCESS, ADD, ADVANCING, AFTER, ALL, ALPHABET, ALPHABETIC, ALPHABETIC_LOWER, ALPHABETIC_UPPER, ALPHANUMERIC, ALPHANUMERIC_EDITED, ALSO, ALTER, ALTERNATE, AND, ANY, ARE, AREA, AREAS, ASCENDING, ASSIGN, AT, AUTHOR, 
	BEFORE, BINARY, BLANK, BLOCK, BOTTOM, BY, 
	CALL, CANCEL, CD, CF, CH, CHARACTER, CHARACTERS, CLASS, CLOCK_UNITS, CLOSE, COBOL, CODE, CODE_SET, COLLATING, COLUMN, COMMA, COMMON, COMMUNICATION, COMP, COMP_0, COMP_1, COMP_2, COMP_3, COMP_4, COMP_5, COMP_6, COMP_X, COMPUTATIONAL, COMPUTATIONAL_0, COMPUTATIONAL_1, COMPUTATIONAL_2, COMPUTATIONAL_3, COMPUTATIONAL_4, COMPUTATIONAL_5, COMPUTATIONAL_6, COMPUTATIONAL_X, COMPUTE, CONFIGURATION, CONTAINS, CONTENT, CONTINUE, CONTROL, CONTROL_AREA, CONTROLS, CONVERTING, COPY, CORR, CORRESPONDING, COUNT, CURRENCY, 
	DATA, DATE, DATE_COMPILED, DATE_WRITTEN, DAY, DAY_OF_WEEK, DE, DEBUG_CONTENTS, DEBUG_ITEM, DEBUG_LINE, DEBUG_NAME, DEBUG_SUB_1, DEBUG_SUB_2, DEBUG_SUB_3, DEBUGGING, DECIMAL_POINT, DECLARATIVES, DELETE, DELIMITED, DELIMITER, DEPENDING, DESCENDING, DESTINATION, DETAIL, DISABLE, DISPLAY, DIVIDE, DIVISION, DOWN, DUPLICATES, DYNAMIC, 
	EGI, ELSE, EMI, ENABLE, END, END_ADD, END_CALL, END_COMPUTE, END_DELETE, END_DIVIDE, END_EVALUATE, END_IF, END_MULTIPLY, END_OF_PAGE, END_PERFORM, END_READ, END_RECEIVE, END_RETURN, END_REWRITE, END_SEARCH, END_START, END_STRING, END_SUBTRACT, END_UNSTRING, END_WRITE, ENTER, ENVIRONMENT, EOP, EQUAL, ERROR, ESI, EVALUATE, EVERY, EXCEPTION, EXIT, EXTEND, EXTERNAL, 
	FALSE, FD, FILE, FILE_CONTROL, FILLER, FINAL, FIRST, FOOTING, FOR, FROM, FUNCTION, 
	GENERATE, GIVING, GLOBAL, GO, GREATER, GROUP, 
	HEADING, HIGH_VALUE, HIGH_VALUES, 
	I_O, I_O_CONTROL, IDENTIFICATION, IF, IN, INDEX, INDEXED, INDICATE, INITIAL, INITIALIZE, INITIATE, INPUT, INPUT_OUTPUT, INSPECT, INSTALLATION, INTO, INVALID, 
	JUST, JUSTIFIED, 
	KEY, 
	LABEL, LAST, LEADING, LEFT, LENGTH, LESS, LIMIT, LIMITS, LINAGE, LINAGE_COUNTER, LINE, LINE_COUNTER, LINES, LINKAGE, LOCK, LOW_VALUE, LOW_VALUES, 
	MEMORY, MERGE, MESSAGE, MODE, MODULES, MORE_LABELS, MOVE, MULTIPLE, MULTIPLY, NATIVE, NEGATIVE, NEXT, NO, NOT, NUMBER, NUMERIC, NUMERIC_EDITED, 
	OBJECT_COMPUTER, OCCURS, OF, OFF, OMITTED, ON, OPEN, OPTIONAL, OR, ORDER, ORGANIZATION, OTHER, OUTPUT, OVERFLOW, 
	PACKED_DECIMAL, PADDING, PAGE, PAGE_COUNTER, PERFORM, PF, PH, PIC, PICTURE, PLUS, POINTER, POSITION, POSITIVE, PRINTING, PROCEDURE, PROCEDURES, PROCEED, PROGRAM, PROGRAM_ID, PURGE, 
	QUEUE, QUOTE, QUOTES, 
	RANDOM, RD, READ, RECEIVE, RECORD, RECORDS, REDEFINES, REEL, REFERENCE, REFERENCES, RELATIVE, RELEASE, REMAINDER, REMOVAL, RENAMES, REPLACE, REPLACING, REPORT, REPORTING, REPORTS, RERUN, RESERVE, RETURN, REVERSED, REWIND, REWRITE, RF, RH, RIGHT, ROUNDED, RUN, 
	SAME, SD, SEARCH, SECTION, SECURITY, SEGMENT, SEGMENT_LIMIT, SELECT, SEND, SENTENCE, SEPARATE, SEQUENCE, SEQUENTIAL, SET, SIGN, SIZE, SORT, SORT_MERGE, SOURCE, SOURCE_COMPUTER, SPACE, SPACES, SPECIAL_NAMES, STANDARD, STANDARD_1, STANDARD_2, START, STATUS, STOP, STRING, SUB_QUEUE_1, SUB_QUEUE_2, SUB_QUEUE_3, SUBTRACT, SUM, SUPER, SUPPRESS, SYMBOLIC, SYNC, SYNCHRONIZED, 
	TALLYING, TAPE, TERMINAL, TERMINATE, TEST, TEXT, THAN, THEN, THROUGH, THRU, TIME, TIMES, TO, TOP, TRAILING, TRUE, TYPE, 
	UNIT, UNSTRING, UNTIL, UP, UPON, USAGE, USE, USING, 
	VALUE, VALUES, VARYING, 
	WHEN, WITH, WORDS, WORKING_STORAGE, WRITE, 
	ZERO, ZEROES, ZEROS;
	//CHECKSTYLE ENABLE LineLength
}
