# Copyright (c) 26.12.2022 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    
    - name: Build with Maven
      env:
        nvdApiKey: ${{ secrets.NVDAPIKEY }}
# Run with z/OS on-the-fly test case
#      run: mvn -B install -Pdc,rat --file pom.xml -Dsonar.xinfo.otf.jobcard="${{ secrets.OTF_JOBCARD }}" -Dsonar.xinfo.otf.port=${{ secrets.OTF_PORT }} -Dsonar.xinfo.otf.pass=${{ secrets.OTF_PASS }} -Dsonar.xinfo.otf.user=${{ secrets.OTF_USER }} -Dsonar.xinfo.otf.server=${{ secrets.OTF_SERVER }} -Dsonar.xinfo.otf.timeout=${{ secrets.OTF_TIMEOUT }}

      run: mvn -B install -Pdc,rat --file pom.xml -Dtest=!*SensorOnTheFlyTest 

    - uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: target      
        
    - uses: actions/upload-artifact@v4
      with:
        name: Plugin
        path: sonar-xinfo-plugin/target/*.jar      
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Plugin
        
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: connect delete
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && rm -vf extensions/plugins/*xinfo* && exit"
        
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*.jar"
        target: ${{ secrets.WORK_DIR }}/extensions/plugins/        
        
    - name: connect restart
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && bin/linux-x86-64/sonar.sh restart && exit"

    - name: cleanup
      run: rm -rf ~/.ssh
      
