name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MAVEN_CACHE_FOLDER: $GITHUB_WORKSPACE/m2
  
    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: env.MAVEN_CACHE_FOLDER 
        # An explicit key for restoring and saving the cache
        key: maven
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.repo.local=env.MAVEN_CACHE_FOLDER