# Copyright (c) 26.12.2022 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build with Maven
      env:
        nvdApiKey: ${{ secrets.NVDAPIKEY }}
# Run with z/OS on-the-fly test case
#      run: mvn -B install -Pdc,rat --file pom.xml -Dsonar.xinfo.otf.jobcard="${{ secrets.OTF_JOBCARD }}" -Dsonar.xinfo.otf.port=${{ secrets.OTF_PORT }} -Dsonar.xinfo.otf.pass=${{ secrets.OTF_PASS }} -Dsonar.xinfo.otf.user=${{ secrets.OTF_USER }} -Dsonar.xinfo.otf.server=${{ secrets.OTF_SERVER }} -Dsonar.xinfo.otf.timeout=${{ secrets.OTF_TIMEOUT }}

      run: mvn -B install -Pdc,rat --file pom.xml -Dtest=!*SensorOnTheFlyTest 
