# Copyright (c) 26.12.2022 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MAVEN_CACHE_FOLDER: $GITHUB_WORKSPACE/m2
  
    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: env.MAVEN_CACHE_FOLDER 
        # An explicit key for restoring and saving the cache
        key: maven
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package -Pcc,release-audit-trail --file pom.xml -Dmaven.repo.local=env.MAVEN_CACHE_FOLDER